modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="foodplusplus"
version="pre"
displayName="Food++"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/SouldbMods/FoodPlusPlus"
logoFile="logo.png"
authors="Souldbminer"

[[dependencies.foodplusplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




